### ISSUE TITLE
[vscode 1.76.0] perforce.editOnSave does not edit the file on save

### ISSUE THREAD

**Issue by sammalt** [mjcrouch/vscode-perforce#252]
**Describe the bug:**
After upgrading VSCode to 1.76.0, saving a file shows the standard VSCode readonly warning when perforce.editOnSave is set true, and the file is not checked out.

**Expected behavior:**
- there should be no warning
- the saved file should be checked out

**To Reproduce:**
1. open a file
2. hit CTRL+S

**Versions & Details:**
 - Perforce extension: 4.15.5
 - VSCode version: 1.76.0
 - Operating System: Win10
 - Are you using a multi-root workspace?: Yes

**Additional context**

The developer tools console spews out this error when opening a file:

<details>

```
mainThreadExtensionService.ts:80 Error: Extension 'mjcrouch.perforce' CANNOT use API proposal: quickDiffProvider.
Its package.json#enabledApiProposals-property declares: [] but NOT quickDiffProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api mjcrouch.perforce
	at b (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:44827)
	at set quickDiffProvider [as quickDiffProvider] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:113879)
	at new m (c:\Users\sammalt\.vscode\extensions\mjcrouch.perforce-4.15.5\dist\extension.js:1:19187)
	at I (c:\Users\sammalt\.vscode\extensions\mjcrouch.perforce-4.15.5\dist\extension.js:7:6036)
	at c:\Users\sammalt\.vscode\extensions\mjcrouch.perforce-4.15.5\dist\extension.js:7:14989
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Q (c:\Users\sammalt\.vscode\extensions\mjcrouch.perforce-4.15.5\dist\extension.js:7:14494)
```

</details>

**Comment by mjcrouch** [comment]
Thanks, given the error, I would say it's the same issue as #251

**Comment by TTimo** [comment]
Any workaround for this? The extension reports this: `The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api mjcrouch.perforce` so maybe there's a quick way?

**Comment by mjcrouch** [comment]
Based on Joao's comment on the issue I raised in vscode, I found a way to work around it in the code - the new build (4.16.6) is being published now so should be available shortly.

**Comment by TTimo** [comment]
Thanks! you're awesome

**Comment by mjcrouch** [comment]
(well, it would have published, but it failed verification because the marketplace badge in the readme is out of date - trying to republish but azure devops has gone down!)

**Comment by mjcrouch** [comment]
ok - published at last - I ended up deleting all the badges from the readme and then updating it to 4.16.7 instead since you can't publish the same version twice.
Only took me about 10 attempts and left a mess, but should be working now

**Comment by Baboonanza** [comment]
Thank you for the quick fix, it was really annoying and I was worried I'd have to wait for a VSCode fix
